Repository Alfresco/alfresco-repository, pull requests merged in 2020-09, with the labels that each got.

#1189 REPO-5339 Improve concurrency of SimplePermissionReference
  src/main/java/org/alfresco/repo/security/permissions/impl/SimplePermissionReference.java
Labels: PR: reviewed-approved

#1217 [MNT-21766]: Significant degradation of performance as file and site count increase
  src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/AlfrescoCreate-RepoTables.sql
  src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/Schema-Reference-ALF.xml
  src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.PostgreSQLDialect/AlfrescoCreate-RepoTables.sql
  src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.PostgreSQLDialect/Schema-Reference-ALF.xml
  src/main/resources/alfresco/dbscripts/db-schema-context.xml
  src/main/resources/alfresco/dbscripts/upgrade/6.3/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/add-indexes-node-transaction.sql
  src/main/resources/alfresco/dbscripts/upgrade/6.3/org.alfresco.repo.domain.dialect.PostgreSQLDialect/add-indexes-node-transaction.sql
  src/main/resources/alfresco/messages/patch-service.properties
  src/main/resources/alfresco/patch/patch-services-context.xml
  src/main/resources/alfresco/repository.properties
Labels: PR: reviewed-approved

#1223 ATS-825 : Updated T-engines to 2.3.5
  .travis.yml
Labels: PR: reviewed-approved

#1224 ATS-825 : Updated T-engines to 2.3.5
  .travis.yml
Labels: PR: reviewed-approved

#1225 [MNT-21766]: Significant degradation of performance as file and site count increase
  src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/AlfrescoCreate-RepoTables.sql
  src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/Schema-Reference-ALF.xml
  src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.PostgreSQLDialect/AlfrescoCreate-RepoTables.sql
  src/main/resources/alfresco/dbscripts/create/org.alfresco.repo.domain.dialect.PostgreSQLDialect/Schema-Reference-ALF.xml
  src/main/resources/alfresco/dbscripts/db-schema-context.xml
  src/main/resources/alfresco/dbscripts/upgrade/6.3/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/add-indexes-node-transaction.sql
  src/main/resources/alfresco/dbscripts/upgrade/6.3/org.alfresco.repo.domain.dialect.PostgreSQLDialect/add-indexes-node-transaction.sql
  src/main/resources/alfresco/messages/patch-service.properties
  src/main/resources/alfresco/patch/patch-services-context.xml
  src/main/resources/alfresco/repository.properties
Labels: PR: reviewed-approved

#1228 SEARCH-2450 Don't expose properties from solr endpoint if the model says not to index them.
  src/main/java/org/alfresco/repo/solr/SOLRTrackingComponentImpl.java
  src/test/java/org/alfresco/repo/solr/SOLRTrackingComponentUnitTest.java
Labels: PR: reviewed-approved

#1229 SEARCH-2450 Don't expose properties from solr endpoint if the model says not to index them. (#1228)
  src/main/java/org/alfresco/repo/solr/SOLRTrackingComponentImpl.java
  src/test/java/org/alfresco/repo/solr/SOLRTrackingComponentUnitTest.java
Labels: PR: unreviewed

#1230 SEARCH-2450 Don't expose properties from solr endpoint if the model says not to index them. (#1228)
  src/main/java/org/alfresco/repo/solr/SOLRTrackingComponentImpl.java
  src/test/java/org/alfresco/repo/solr/SOLRTrackingComponentUnitTest.java
Labels: PR: unreviewed

#1231 SEARCH-2450 Don't expose properties from solr endpoint if the model says not to index them. (#1228)
  src/main/java/org/alfresco/repo/solr/SOLRTrackingComponentImpl.java
  src/test/java/org/alfresco/repo/solr/SOLRTrackingComponentUnitTest.java
Labels: PR: unreviewed

#1232 Fix/MNT-21800 CMIS Web Service Check Out returns error
  src/main/java/org/alfresco/opencmis/TransactionAwareHolder.java
Labels: PR: partially-approved

#1234 Fix/MNT-21800 CMIS Web Service Check Out returns error
  src/main/java/org/alfresco/opencmis/TransactionAwareHolder.java
Labels: PR: reviewed-approved

#1233 Fix/MNT-21800 CMIS Web Service Check Out returns error
  src/main/java/org/alfresco/opencmis/TransactionAwareHolder.java
Labels: PR: reviewed-approved
