Repository Alfresco/alfresco-repository, pull requests merged in 2020-10, with the labels that each got.

#1235 MNT-21871 : [Security] Multiple jackson-databind vulnerabilities
  pom.xml
Labels: PR: partially-approved

#1204 REPO-5325: TMDQ accelerated table support detection
  src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryBuilderPredicatePartCommand.java
  src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngine.java
  src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/PropertySupport.java
  src/main/java/org/alfresco/repo/search/impl/solr/DbCmisQueryLanguage.java
Labels: PR: reviewed-approved

#1244 MNT-21871 : [Security] Multiple jackson-databind vulnerabilities
  pom.xml
Labels: PR: partially-approved

#1256 Fix/acs 701 check duplicate prefix content model
  pom.xml
  src/main/java/org/alfresco/repo/dictionary/CustomModelServiceImpl.java
  src/main/java/org/alfresco/repo/dictionary/DictionaryModelType.java
  src/main/java/org/alfresco/repo/dictionary/ModelValidator.java
  src/main/java/org/alfresco/repo/dictionary/ModelValidatorImpl.java
  src/main/resources/alfresco/core-services-context.xml
  src/main/resources/alfresco/minimal-context.xml
  src/test/java/org/alfresco/AppContext03TestSuite.java
  src/test/java/org/alfresco/repo/dictionary/ModelValidatorTest.java
Labels: PR: unreviewed

#1253 MNT-21936 : Audit query Rest API does not return the correct totalItems
  src/main/java/org/alfresco/repo/audit/AuditComponent.java
  src/main/java/org/alfresco/repo/audit/AuditComponentImpl.java
  src/main/java/org/alfresco/repo/audit/AuditServiceImpl.java
  src/main/java/org/alfresco/repo/domain/audit/AuditDAO.java
  src/main/java/org/alfresco/repo/domain/audit/ibatis/AuditDAOImpl.java
  src/main/java/org/alfresco/service/cmr/audit/AuditService.java
  src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/audit-common-SqlMap.xml
Labels: PR: partially-approved

#1261 MNT-21936 : Audit query Rest API does not return the correct totalIte…
  src/main/java/org/alfresco/repo/audit/AuditComponent.java
  src/main/java/org/alfresco/repo/audit/AuditComponentImpl.java
  src/main/java/org/alfresco/repo/audit/AuditServiceImpl.java
  src/main/java/org/alfresco/repo/domain/audit/AuditDAO.java
  src/main/java/org/alfresco/repo/domain/audit/ibatis/AuditDAOImpl.java
  src/main/java/org/alfresco/service/cmr/audit/AuditService.java
  src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/audit-common-SqlMap.xml
Labels: PR: reviewed-approved

#1260 MNT-21936 : Audit query Rest API does not return the correct totalIte…
  src/main/java/org/alfresco/repo/audit/AuditComponent.java
  src/main/java/org/alfresco/repo/audit/AuditComponentImpl.java
  src/main/java/org/alfresco/repo/audit/AuditServiceImpl.java
  src/main/java/org/alfresco/repo/domain/audit/AuditDAO.java
  src/main/java/org/alfresco/repo/domain/audit/ibatis/AuditDAOImpl.java
  src/main/java/org/alfresco/service/cmr/audit/AuditService.java
  src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/audit-common-SqlMap.xml
Labels: PR: reviewed-approved

#1262 MNT-21936 : Audit query Rest API does not return the correct totalIte…
  src/main/java/org/alfresco/repo/audit/AuditComponent.java
  src/main/java/org/alfresco/repo/audit/AuditComponentImpl.java
  src/main/java/org/alfresco/repo/audit/AuditServiceImpl.java
  src/main/java/org/alfresco/repo/domain/audit/AuditDAO.java
  src/main/java/org/alfresco/repo/domain/audit/ibatis/AuditDAOImpl.java
  src/main/java/org/alfresco/service/cmr/audit/AuditService.java
  src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/audit-common-SqlMap.xml
Labels: PR: reviewed-approved

#1265 [SEARCH-2465]
  pom.xml
  src/main/java/org/alfresco/repo/event2/ChildAssociationEventConsolidator.java
  src/main/java/org/alfresco/repo/event2/EventConsolidator.java
  src/main/java/org/alfresco/repo/event2/EventGenerator.java
  src/main/java/org/alfresco/repo/event2/EventJSONSchema.java
  src/main/java/org/alfresco/repo/event2/EventType.java
  src/main/java/org/alfresco/repo/event2/PeerAssociationEventConsolidator.java
  src/test/java/org/alfresco/repo/event2/AbstractContextAwareRepoEvent.java
  src/test/java/org/alfresco/repo/event2/ChildAssociationRepoEventIT.java
  src/test/java/org/alfresco/repo/event2/CreateRepoEventIT.java
  src/test/java/org/alfresco/repo/event2/DeleteRepoEventIT.java
  src/test/java/org/alfresco/repo/event2/EventJSONSchemaUnitTest.java
  src/test/java/org/alfresco/repo/event2/PeerAssociationRepoEventIT.java
  src/test/java/org/alfresco/repo/event2/UpdateRepoEventIT.java
Labels: PR: reviewed-approved

#1270 Feature/repo 5369 acl resolution and paging inside db query engine
  src/main/java/org/alfresco/ibatis/SqlSessionMetricsWrapper.java
  src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
  src/main/java/org/alfresco/repo/domain/node/ibatis/NodeDAOImpl.java
  src/main/java/org/alfresco/repo/search/impl/lucene/PagingLuceneResultSet.java
  src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngine.java
  src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBResultSet.java
  src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/metadata-query-SqlMap.xml
  src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/metadata-query-common-SqlMap.xml
  src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/metadata-query-SqlMap.xml
  src/main/resources/alfresco/subsystems/Search/common-search-context.xml
  src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngineTest.java
  src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/NodePermissionAssessorTest.java
Labels: PR: reviewed-approved

#1285 Feature/acs 247 relational query accelerator
  src/main/java/org/alfresco/ibatis/SqlSessionMetricsWrapper.java
  src/main/java/org/alfresco/repo/domain/node/AbstractNodeDAOImpl.java
  src/main/java/org/alfresco/repo/domain/node/ibatis/NodeDAOImpl.java
  src/main/java/org/alfresco/repo/search/impl/lucene/PagingLuceneResultSet.java
  src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryBuilderPredicatePartCommand.java
  src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngine.java
  src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBResultSet.java
  src/main/java/org/alfresco/repo/search/impl/querymodel/impl/db/PropertySupport.java
  src/main/java/org/alfresco/repo/search/impl/solr/DbCmisQueryLanguage.java
  src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/metadata-query-SqlMap.xml
  src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.Dialect/metadata-query-common-SqlMap.xml
  src/main/resources/alfresco/ibatis/org.alfresco.repo.domain.dialect.MySQLInnoDBDialect/metadata-query-SqlMap.xml
  src/main/resources/alfresco/subsystems/Search/common-search-context.xml
  src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/DBQueryEngineTest.java
  src/test/java/org/alfresco/repo/search/impl/querymodel/impl/db/NodePermissionAssessorTest.java
Labels: PR: unreviewed
