Repository Alfresco/alfresco-repository, pull requests merged in 2020-04, with the labels that each got.

#936 Repo 5043 integration tests
  pom.xml
  src/test/java/org/alfresco/AppContext06TestSuite.java
  src/test/java/org/alfresco/repo/event2/AbstractContextAwareRepoEvent.java
  src/test/java/org/alfresco/repo/event2/CreateRepoEventIT.java
  src/test/java/org/alfresco/repo/event2/DeleteRepoEventIT.java
  src/test/java/org/alfresco/repo/event2/EventGeneratorTest.java
  src/test/java/org/alfresco/repo/event2/UpdateRepoEventIT.java
Labels: PR: unreviewed

#920 Fix/mnt 20916 log4j configuration hierarchy
  src/main/java/org/alfresco/repo/admin/Log4JHierarchyInit.java
  src/test/java/org/alfresco/repo/admin/Log4JHierarchyInitTest.java
  src/test/resources/log4j/custom-log4j.properties
  src/test/resources/log4j/log4j-test-context.xml
  src/test/resources/log4j/log4j.properties
Labels: PR: draft

#951 MNT-21510 - Update Freemarker version to 2.3.20-alfresco-patched-2020…
  pom.xml
Labels: PR: merged

#968 REPO-5101-Update Repo Event Integration Tests
  src/test/java/org/alfresco/repo/event2/AbstractContextAwareRepoEvent.java
  src/test/java/org/alfresco/repo/event2/CreateRepoEventIT.java
  src/test/java/org/alfresco/repo/event2/DeleteRepoEventIT.java
  src/test/java/org/alfresco/repo/event2/UpdateRepoEventIT.java
Labels: PR: partially-approved
